import React, { useState } from 'react';
import { GraduationCap, Play, Loader2, AlertCircle, Download, FileText, Sparkles, CheckSquare, ClipboardList } from 'lucide-react';
import { InputPanel } from './components/InputPanel';
import { GradeGauge } from './components/GradeGauge';
import { RubricHeatmap } from './components/RubricHeatmap';
import { RedPen } from './components/RedPen';
import { StarSuggestions } from './components/StarSuggestions';
import { DetailedFeedbackModal } from './components/DetailedFeedbackModal';
import { analyzeAssignment } from './services/geminiService';
import { InputData, AppState } from './types';

const initialInput: InputData = { type: 'text', content: '' };

function App() {
  const [brief, setBrief] = useState<InputData>(initialInput);
  const [submission, setSubmission] = useState<InputData>(initialInput);
  const [state, setState] = useState<Omit<AppState, 'brief' | 'submission'>>({
    isAnalyzing: false,
    result: null,
    error: null,
  });
  const [showDetailedFeedback, setShowDetailedFeedback] = useState(false);

  const handleAnalyze = async () => {
    if (!brief.content || !submission.content) {
        setState(prev => ({ ...prev, error: "Please provide both a brief and a submission." }));
        return;
    }

    setState({ isAnalyzing: true, result: null, error: null });

    try {
      const result = await analyzeAssignment(brief, submission);
      setState({ isAnalyzing: false, result, error: null });
    } catch (err: any) {
      setState({ 
        isAnalyzing: false, 
        result: null, 
        error: err.message || "An error occurred during analysis. Please check your API Key or try again." 
      });
    }
  };

  const handleExport = () => {
    if (!state.result) return;
    const { overallGrade, overallScore, summary, assignmentTaskSummary, rubricContext, rubricBreakdown, criticalImprovements, reachingForTheStars } = state.result;
    
    let content = `ACADEMIC AUDIT REPORT\n`;
    content += `=====================\n\n`;
    content += `OVERALL GRADE: ${overallGrade} (${overallScore}/100)\n\n`;
    content += `EXECUTIVE SUMMARY\n-----------------\n${summary}\n\n`;
    content += `ASSIGNMENT CONTEXT\n------------------\n`;
    content += `Tasks Identified: ${assignmentTaskSummary}\n`;
    content += `Rubric Used: ${rubricContext}\n\n`;
    content += `RUBRIC BREAKDOWN\n----------------\n`;
    rubricBreakdown.forEach(item => {
        content += `[${item.performance}] ${item.criterion}: ${item.score}/${item.maxScore}\n`;
        content += `> ${item.feedback}\n\n`;
    });
    content += `CRITICAL IMPROVEMENTS\n---------------------\n`;
    criticalImprovements.forEach(item => {
        content += `- ${item}\n`;
    });
    
    if (reachingForTheStars && reachingForTheStars.length > 0) {
        content += `\nREACHING FOR THE STARS (Exceptional Steps)\n------------------------------------------\n`;
        reachingForTheStars.forEach(item => {
            content += `* ${item}\n`;
        });
    }

    content += `\n\nGenerated by Academic Audit Pro`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Audit_Report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-screen bg-zinc-50 text-zinc-900 font-sans overflow-hidden">
      
      {/* LEFT SIDEBAR: Branding + Inputs + Context */}
      <aside className="w-80 lg:w-96 flex-shrink-0 bg-white border-r border-zinc-200 flex flex-col z-20 shadow-[4px_0_24px_rgba(0,0,0,0.02)]">
          {/* Branding */}
          <div className="h-16 px-6 flex items-center gap-3 border-b border-zinc-100 bg-white flex-shrink-0">
            <div className="p-1.5 bg-indigo-600 rounded-lg shadow-lg shadow-indigo-900/20">
                <GraduationCap size={18} className="text-white" strokeWidth={2} />
            </div>
            <div>
                <h1 className="text-sm font-bold tracking-tight leading-none text-zinc-900">Academic Audit Pro</h1>
                <p className="text-[10px] text-zinc-400 font-medium">Automated Assessment Intelligence</p>
            </div>
          </div>

          {/* Scrollable Sidebar Content */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-thin">
              
              {/* Inputs */}
              <div className="space-y-4">
                  <div>
                    <h3 className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Input Data</h3>
                    <div className="flex flex-col gap-3">
                        <div className="h-20">
                            <InputPanel 
                                title="Assignment Brief" 
                                subLabel="Rubric / Instructions"
                                data={brief}
                                onChange={setBrief}
                            />
                        </div>
                        <div className="h-20">
                            <InputPanel 
                                title="Student Submission" 
                                subLabel="PDF / Text / IPYNB"
                                data={submission}
                                onChange={setSubmission}
                            />
                        </div>
                    </div>
                  </div>

                  {/* Action Button */}
                  <button
                    onClick={handleAnalyze}
                    disabled={state.isAnalyzing || !brief.content || !submission.content}
                    className={`w-full h-12 px-6 rounded-lg flex items-center justify-center gap-2 transition-all transform active:scale-[0.98] ${
                      state.isAnalyzing 
                        ? 'bg-zinc-100 text-zinc-400 cursor-not-allowed border border-zinc-200' 
                        : (!brief.content || !submission.content)
                            ? 'bg-zinc-100 text-zinc-400 cursor-not-allowed border border-zinc-200'
                            : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-md hover:shadow-lg shadow-indigo-500/20 border border-indigo-500'
                    }`}
                  >
                    {state.isAnalyzing ? (
                      <>
                        <Loader2 className="animate-spin" size={16} />
                        <span className="text-xs font-bold uppercase tracking-wider opacity-80">Analysing...</span>
                      </>
                    ) : (
                      <>
                        <Play size={16} fill="currentColor" />
                        <span className="text-xs font-bold uppercase tracking-wider">Run Audit</span>
                      </>
                    )}
                  </button>

                  {state.error && (
                    <div className="text-[11px] font-medium text-rose-600 bg-rose-50 border border-rose-100 p-3 rounded-lg flex items-start gap-2 leading-tight animate-in fade-in">
                        <AlertCircle size={14} className="shrink-0 mt-0.5" /> {state.error}
                    </div>
                  )}
              </div>

              {/* Context - Shown after analysis */}
              {state.result && (
                  <div className="space-y-6 pt-6 border-t border-zinc-100 animate-fade-in">
                      <div>
                         <h3 className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                            <CheckSquare size={14} /> Required Tasks
                         </h3>
                         <div className="bg-zinc-50 rounded-lg border border-zinc-100 p-3 text-xs text-zinc-600 leading-relaxed">
                             {state.result.assignmentTaskSummary}
                         </div>
                      </div>

                      <div>
                         <h3 className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                            <ClipboardList size={14} /> Grading Rubric
                         </h3>
                         <div className="bg-zinc-50 rounded-lg border border-zinc-100 p-3 text-xs text-zinc-600 leading-relaxed">
                             {state.result.rubricContext}
                         </div>
                      </div>
                  </div>
              )}
          </div>
          
          {/* Sidebar Footer */}
          <div className="p-4 border-t border-zinc-100 bg-zinc-50/50 text-[10px] text-zinc-400 text-center">
              v1.0 &bull; Powered by Google Gemini
          </div>
      </aside>

      {/* MAIN CONTENT AREA */}
      <main className="flex-1 overflow-y-auto bg-zinc-50/50 relative">
        {!state.result ? (
            <div className="absolute inset-0 flex flex-col items-center justify-center text-zinc-400 p-10 text-center">
                <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mb-6 shadow-[0_8px_30px_rgba(0,0,0,0.04)] border border-zinc-100">
                    <Sparkles size={40} className="text-indigo-200" />
                </div>
                <h2 className="text-xl font-semibold text-zinc-700 mb-2">Ready to Audit</h2>
                <p className="max-w-md text-sm leading-relaxed text-zinc-500">
                    Upload your documents on the left to generate a comprehensive academic review.
                </p>
            </div>
        ) : (
            <div className="max-w-[1200px] mx-auto p-8 space-y-8 pb-20 animate-fade-in">
                
                {/* Top Card: Summary & Grade */}
                <div className="flex flex-col xl:flex-row gap-8 items-start justify-between bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
                    <div className="flex-1">
                        <div className="flex items-center gap-2 mb-4">
                             <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-indigo-50 text-indigo-600 uppercase tracking-wider border border-indigo-100">
                                 Audit Completed
                             </span>
                        </div>
                        <p className="text-zinc-700 text-base leading-relaxed">
                            {state.result.summary}
                        </p>
                    </div>
                    
                    {/* Grade Gauge + Actions */}
                    <div className="flex-shrink-0 border-t xl:border-t-0 xl:border-l border-zinc-100 pt-6 xl:pt-0 xl:pl-10 flex flex-col items-center justify-center gap-5 w-full xl:w-auto">
                        <GradeGauge score={state.result.overallScore} grade={state.result.overallGrade} />
                        
                        <div className="flex gap-3 w-full sm:w-auto">
                            <button 
                                onClick={() => setShowDetailedFeedback(true)}
                                className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 text-xs font-medium text-indigo-600 hover:text-indigo-700 bg-indigo-50 hover:bg-indigo-100 px-4 py-2 rounded-md border border-indigo-100 transition-all"
                            >
                                <FileText size={14} />
                                Detailed Feedback
                            </button>
                            <button 
                                onClick={handleExport}
                                className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 text-xs font-medium text-zinc-500 hover:text-zinc-900 bg-white hover:bg-zinc-50 px-4 py-2 rounded-md border border-zinc-200 transition-all"
                            >
                                <Download size={14} />
                                Export
                            </button>
                        </div>
                    </div>
                </div>

                {/* Main Grid: Heatmap & Red Pen */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Rubric Heatmap */}
                    <section className="bg-white rounded-2xl border border-zinc-200 shadow-sm overflow-hidden h-full">
                         <div className="p-5 border-b border-zinc-100 bg-zinc-50/30 flex justify-between items-center">
                            <h3 className="font-semibold text-zinc-800 flex items-center gap-2">
                                <div className="w-1.5 h-4 bg-indigo-500 rounded-full"></div>
                                Rubric Heatmap
                            </h3>
                         </div>
                         <div className="p-6">
                            <RubricHeatmap items={state.result.rubricBreakdown} />
                         </div>
                    </section>

                    {/* Red Pen */}
                    <section className="bg-white rounded-2xl border border-zinc-200 shadow-sm overflow-hidden flex flex-col h-full">
                         <div className="p-5 border-b border-zinc-100 bg-rose-50/30 flex justify-between items-center">
                            <h3 className="font-semibold text-zinc-800 flex items-center gap-2">
                                <div className="w-1.5 h-4 bg-rose-500 rounded-full"></div>
                                The Red Pen
                            </h3>
                            <span className="text-xs font-medium text-rose-600 bg-rose-100 px-2 py-0.5 rounded-full">
                                {state.result.criticalImprovements.length} Issues
                            </span>
                         </div>
                         <div className="p-6 flex-1">
                            <RedPen improvements={state.result.criticalImprovements} />
                         </div>
                         <div className="p-4 bg-zinc-50 border-t border-zinc-100 text-center mt-auto">
                             <p className="text-xs text-zinc-400 italic">
                                 These items represent the most significant opportunities for grade improvement.
                             </p>
                         </div>
                    </section>
                </div>

                {/* Reaching for the Stars */}
                <StarSuggestions suggestions={state.result.reachingForTheStars} />

            </div>
        )}

        {/* Modals */}
        {showDetailedFeedback && state.result && (
            <DetailedFeedbackModal 
                result={state.result} 
                onClose={() => setShowDetailedFeedback(false)} 
            />
        )}
      </main>

      <style>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.5s ease-out forwards;
        }
      `}</style>
    </div>
  );
}

export default App;